name: best_app_ever
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.19

flutter:
  uses-material-design: true
